### ISSUE TITLE
Register targets must be pointers

### ISSUE THREAD

**Issue by anacrolix** [riyaz-ali/sqlite#15]
I don't think it's documented, but the things you register must be pointer types, or at least I think it's that way (due to mattn/pointer). Let me know if I have this wrong.

**Comment by riyaz-ali** [comment]
Apologies for being 10 months late to this issue 😅 

For future reference, it turns out that is not the case. `mattn/go-pointer` works just fine even with non-pointer types (I guess because it stores [_the `interface{}` structure and not the actual object_](https://stackoverflow.com/a/23148998/6611700) but I don't have enough expertise to comment on this).

What's more important to realise is that [the normal caveats of value vs. pointer receiver](https://stackoverflow.com/a/27775558/6611700) applies.

Here's a modified version of the slightly `Upper` function snippet from `func_scalar_test.go`:

```golang
type Upper struct{ c int }

func (m Upper) Args() int           { return 1 }
func (m Upper) Deterministic() bool { return true }
func (m Upper) Apply(ctx *Context, values ...Value) {
	_, _ = fmt.Fprintf(os.Stderr, "c: %d\n", m.c)
	m.c += 1 // updates m.c in the copy 
	ctx.ResultText(strings.ToUpper(values[0].Text()))
}
```
