### ISSUE TITLE
Multiple entrypoints?

### ISSUE THREAD

**Issue by asg017** [riyaz-ali/sqlite#9]
Hey @riyaz-ali !

First off, like always - I'm deeply appreciative of this project and your work on it!

I was wondering what you think about whether this can support multiple entrypoints in a single compiled shared library. I know currently there's a single entrypoint called `sqlite3_extension_init` (or `SQLITE3_INIT_FN` [if overridden](https://github.com/riyaz-ali/sqlite/blob/master/extension.c#L11-L22)), but I have a few use-cases for wanting multiple entrypoints. 

For example, in [sqlite-http](https://github.com/asg017/sqlite-http), there's 2 version of the library: the 1st has all functions available that make HTTP requests, and the 2nd version has all the HTTP request functions removed (for security reasons). 

But since there's only 1 entrypoint available, I [have to build 2 versions of the extension](https://github.com/asg017/sqlite-http/blob/main/Makefile#L45-L55), with a custom `-X main.OmitNet=1` compile-time flag that determines whether to exclude the requests functions. 

```sql
-- load the normal sqlite-http extension with all functions
.load ./http0

-- load the "no network" version of sqlite-http without the HTTP request functions
.load ./http0-no-net
```
Having to download different binaries for the same library isn't ideal. Instead, I'd like to include 1 binary with two entrypoints, like so:

```sql
-- load the normal sqlite-http extension with all functions
.load ./http0 sqlite3_http_init

-- load the "no network" version of sqlite-http without the HTTP request functions
.load ./http0 sqlite3_http_nonet_init
```

Same binary, two entrypoints, best of both worlds!

I've got other extensions in the work that would really benefit from multiple entrypoints, as well. I'm not 100% sure how feasible it is, because cgo seems pretty annoying to work with, but I'm will to try it out and send up a PR if it's something you're interested in!

**Comment by riyaz-ali** [comment]
Hey @asg017 👋 

Sure! having multiple entry-points sounds like a good feature. I gave it a try in #10

From my testing, I found that sqlite3 relies on distinct symbols (function names) to enable bundling multiple extensions. But doing it entirely within the scope of the library is not feasible (at-least from what I've found). 

But there are ways in which the embedding package can do it by adding a boilerplate `c` source file, and enabling `cgo` for package compilation (since we're anyways relying on cgo for sqlite3 this shouldn't be a problem).

In #10, I've extended the library's api to facilitate this sort of an arrangement. It's complete on its own but allows the dependent package to at least have some way to configure things, if they need to.

Also, #10 shouldn't impact normal / simpler, single extension use-cases.

Checkout a simple demonstration at https://gist.github.com/riyaz-ali/53959b1b7addb107e50340359e553ddd

**Comment by asg017** [comment]
@riyaz-ali , thank you for your quick response and your extremely thoughtful approach!

I tried this out with sqlite-http, and there are a few kinks I have to work through (all from my end), this is working as expected! 🎉 

I really like the backward-compatibility and how customized you can make it - I don't think requiring a boilerplate `c` file is a big deal at all. I also really appreciate your example - those compiler flags alone saved me hours of trying/failing on my own...
